{"name": "test_hr_location_postal_code_validity", "status": "failed", "statusDetails": {"message": "AssertionError: Count of row is not valid. Actual row count is 2\nassert 2 == 0", "trace": "def test_hr_location_postal_code_validity():\n        cursor, conn = connection.mssql_connect(Credentials.server,\n                                                Credentials.user,\n                                                Credentials.password,\n                                                Credentials.database,\n                                                Credentials.port)\n        cursor.execute(SQL_scripts.hr_location_postal_code_validity_query())\n        results = len(pd.DataFrame(cursor.fetchall()).index)\n>       assert results == 0, global_enums.WRONG_COUNT_OF_ROWS(results)\nE       AssertionError: Count of row is not valid. Actual row count is 2\nE       assert 2 == 0\n\ntests\\test_case.py:64: AssertionError"}, "start": 1652359470433, "stop": 1652359470446, "uuid": "b0fb0c04-84c8-4a65-84f4-ce310c2b3d16", "historyId": "6dd1ff11326b09908c18093dc8fba7a5", "testCaseId": "6b4b868f539f78e6c7509e5e080c5329", "fullName": "tests.test_case#test_hr_location_postal_code_validity", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_case"}, {"name": "host", "value": "EPBYMINW0E13"}, {"name": "thread", "value": "5864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_case"}]}